spring:
  application:
    name: gateway
  config:
    import: "optional:nacos:gateway.yaml"
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.52.128:8848
      config:
        server-addr: 192.168.52.128:8848
        file-extension: properties
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"


